Vagrant.configure("2") do |config|
  config.vm.define "server" do |s|
    s.vm.box = "bento/ubuntu-24.04"
    s.vm.provider :virtualbox
      (0..2).each do |i|
        s.vm.disk :disk, size: "5GB", name: "disk-#{i}"
      end
  end
end
